//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 区域列表 的本地化字符串。
        /// </summary>
        internal static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础配置 的本地化字符串。
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信标列表 的本地化字符串。
        /// </summary>
        internal static string Beacons {
            get {
                return ResourceManager.GetString("Beacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组列表 的本地化字符串。
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS位置查询配置 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室内位置查询配置 的本地化字符串。
        /// </summary>
        internal static string LocationInDoor {
            get {
                return ResourceManager.GetString("LocationInDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mnis配置 的本地化字符串。
        /// </summary>
        internal static string Mnis {
            get {
                return ResourceManager.GetString("Mnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端列表 的本地化字符串。
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中继台配置 的本地化字符串。
        /// </summary>
        internal static string Repeater {
            get {
                return ResourceManager.GetString("Repeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存完成 的本地化字符串。
        /// </summary>
        internal static string SaveComplete {
            get {
                return ResourceManager.GetString("SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string SaveFailure {
            get {
                return ResourceManager.GetString("SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存{0}{1} 的本地化字符串。
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工列表 的本地化字符串。
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户列表 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车载台配置 的本地化字符串。
        /// </summary>
        internal static string VehicleStation {
            get {
                return ResourceManager.GetString("VehicleStation", resourceCulture);
            }
        }
    }
}
