//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher.resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Amap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Amap() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dispatcher.resource.Amap", typeof(Amap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML&gt;
        ///&lt;!-- saved from url=(0016)http://localhost --&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;title&gt;地图显示&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body{
        ///			margin:0;
        ///			height:100%;
        ///			width:100%;
        ///			position:absolute;
        ///			font-size:12px;
        ///		}
        ///		#mapContainer{
        ///			position: absolute;
        ///			top:0;
        ///			left: 0;
        ///			right:0;
        ///			bottom:0;
        ///			height:100%
        ///		}
        ///		
        ///		html{
        ///			margin:0;
        ///			height:100%;
        ///			font-size:12px;
        ///		}
        ///
        ///		
        ///		#tip{
        ///			position:absolute;
        ///			bottom:20px;
        ///			right:0;
        ///			 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap infowin {
            get {
                object obj = ResourceManager.GetObject("infowin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt; 
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title&gt;html5背景&lt;/title&gt;
        ///    
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    *{margin:0;padding:0;list-style-type:none;}
        ///    a,img{border:0;}
        ///    &lt;/style&gt;
        ///    &lt;script&gt;
        ///	/*! jQuery v1.8.3 jquery.com | jquery.org/license */
        ///(function(e,t){function _(e){var t=M[e]={};return v.each(e.split(y),function(e,n){t[n]=!0}),t}function H(e,n,r){if(r===t&amp;&amp;e.nodeType===1){var i=&quot;data-&quot;+n.replace(P,&quot;-$1&quot;).toLowerCase();r=e.getAttr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap msg_close_18_18_n {
            get {
                object obj = ResourceManager.GetObject("msg_close_18_18_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pos_radio_36_77 {
            get {
                object obj = ResourceManager.GetObject("pos_radio_36_77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pos_ride_36_77 {
            get {
                object obj = ResourceManager.GetObject("pos_ride_36_77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pos_staff_36_77 {
            get {
                object obj = ResourceManager.GetObject("pos_staff_36_77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pos_vehicle_36_77 {
            get {
                object obj = ResourceManager.GetObject("pos_vehicle_36_77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap radio_40_40 {
            get {
                object obj = ResourceManager.GetObject("radio_40_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ride_40_40 {
            get {
                object obj = ResourceManager.GetObject("ride_40_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap staff_40_40 {
            get {
                object obj = ResourceManager.GetObject("staff_40_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 var pos = {&apos;count&apos;:1,&apos;position&apos;:[{&apos;id&apos;:1,&apos;type&apos;:0,&apos;count&apos;:5,&apos;color&apos;:&apos;#8888ff&apos;,&apos;map&apos;:[{&apos;lng&apos;:2,&apos;lat&apos;:2,&apos;date&apos;:&apos;2015/8/13&apos;,&apos;time&apos;:&apos;17:15:18&apos;,&apos;alt&apos;:0,&apos;speed&apos;:0,&apos;mlon&apos;:2,&apos;mlat&apos;:2},{&apos;lng&apos;:1,&apos;lat&apos;:1,&apos;date&apos;:&apos;2015/8/13&apos;,&apos;time&apos;:&apos;17:15:13&apos;,&apos;alt&apos;:0,&apos;speed&apos;:0,&apos;mlon&apos;:1,&apos;mlat&apos;:1},{&apos;lng&apos;:12,&apos;lat&apos;:12,&apos;date&apos;:&apos;2015/8/13&apos;,&apos;time&apos;:&apos;16:59:11&apos;,&apos;alt&apos;:0,&apos;speed&apos;:0,&apos;mlon&apos;:12,&apos;mlat&apos;:12},{&apos;lng&apos;:11,&apos;lat&apos;:11,&apos;date&apos;:&apos;2015/8/13&apos;,&apos;time&apos;:&apos;16:59:06&apos;,&apos;alt&apos;:0,&apos;speed&apos;:0,&apos;mlon&apos;:11,&apos;mlat&apos;:11},{&apos;lng&apos;:7,&apos;lat&apos;:7,&apos;date&apos;:&apos;2015/8/13&apos;,&apos;ti... 的本地化字符串。
        /// </summary>
        internal static string trace {
            get {
                return ResourceManager.GetString("trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap vehicle_40_40 {
            get {
                object obj = ResourceManager.GetObject("vehicle_40_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
